### ISSUE TITLE
DialogHost not shown when Dialog Content contains ListBox

### ISSUE THREAD

**Issue by Mrxx99** [AvaloniaUtils/DialogHost.Avalonia#35] opened 2023-08-03 20:48 UTC
I have a minimal sample project where the DialogHost content contains a ListBox and a Button, when the ListBox is there the Dialog is not shown, if the ListBox is not there the Dialog is shown properly.

You can check with the project AvaloniaMatrixInvertIssue_v11 here:
https://github.com/Mrxx99/AvaloniaDialogHostAndAsyncImageLoaderIssue

Just lunch the project and click the "Show Dialog" button -> dialog will not show
then stop, remove or replace the ListBox and try again -> now it will work

(you can ignore the other projects and the async image loader in the repo as there was initial an issue when both were used together with avalonia 11 preview6)

**Comment by Bip901** [comment] 2023-08-05 11:24
Just experienced the same issue - `System.InvalidOperationException` is thrown with the message "Transform is not invertible".

This issue is new to the Avalonia 11 release.

Here's a minimal project to reproduce the issue - just run and click the button:

[avaloniatest.zip](https://github.com/AvaloniaUtils/DialogHost.Avalonia/files/12266907/avaloniatest.zip)

Screenshot:

![Screenshot 2023-08-05 141849](https://github.com/AvaloniaUtils/DialogHost.Avalonia/assets/74911767/1cf5aaf7-5337-4847-a7a3-655a10b0fd4c)

**Comment by SKProCH** [comment] 2023-08-05 22:30
When I click the button in all above examples here, I didn't get any exception, seems like because of this weird issue: https://github.com/AvaloniaUI/Avalonia/issues/12388

I'll try to investigate it, but currently I doesn't know how.

**Comment by SKProCH** [comment] 2023-08-05 22:35
@Bip901, can you provide an full exception details (or at least stacktrace)?

**Comment by SKProCH** [comment] 2023-08-05 22:41
Seems like setting `DisableOpeningAnimation="True"` for `DialogHost` will prevent this from appearing.

**Comment by SKProCH** [comment] 2023-08-05 22:59
Also, seems like this is related to `VirualizingStackPanel`, since if we change it to something else (e.g. StackPanel), this works fine:
```xaml
<ListBox>
  <ListBox.ItemsPanel>
    <ItemsPanelTemplate>
      <VirtualizingStackPanel></VirtualizingStackPanel>
    </ItemsPanelTemplate>
  </ListBox.ItemsPanel>
  <ListBoxItem>test</ListBoxItem>
</ListBox>
```

**Comment by SKProCH** [comment] 2023-08-05 23:33
Fixed with the workaround.

**Closed** 2023-08-05 23:33 UTC
Labels: bug

**Comment by SKProCH** [comment] 2023-08-05 23:36
Will be available as v0.7.6 on nuget in near future.

**Comment by Bip901** [comment] 2023-08-06 04:42
Awesome, quick fix and detailed explanation -  thank you!

Note that I also experienced a hang rather than an exception - I just noticed an InvalidOperationException in the logs so I changed the Visual Studio settings to break on InvalidOperationException. Since it occurs on a background thread, I could resume debugging and also observe that the app keeps running in a frozen state.

**Comment by SKProCH** [comment] 2023-08-06 10:20
Strange, but if I set an exception breakpoints in Rider, it doesn't trigger.
